name: rap-soft-joystick
base: core18
version: '0.1.0'
summary: A soft joystick for robots running ROS melodic
description: |
  A small ROS node plus web server with user interface to enable a user
  connected to the robots network to joystick the robot via a web app on
  their phone or other connected device.

grade: devel # must be 'stable' to release into candidate/stable channels
#confinement: devmode # use 'strict' once you have the right plugs and slots
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
#  ros-node-and-server:
#    source: .
#    plugin: nodejs
  # ignore:
  #   plugin: catkin
  #   source: catkin_ws
  test:
    source: test/
    plugin: dump
    organize:
      test.sh: bin/
  health:
    source: health/
    plugin: dump
    # organize:
    #   main.js: bin/main.js
    # filesets:
    #   myfiles: [ health/* ]
    stage-packages:
      - nodejs

plugs:
  myros:
    interface: system-files
    read:
    - /opt/ros

apps:
  test:
    command: bin/test.sh
    plugs: [network, network-bind, myros]
  health:
    command: node $SNAP/main.js
    plugs: [network, network-bind]
    daemon: simple
