# build and deploy the portal
name: DeployPortal

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
    - 'cloud/portal/**'
    # later change this to a specific branch
  pull_request:
    branches: [ ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # build the portal (meteor build) on github
  buildPortal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build bundle
        run: |
          curl https://install.meteor.com/ | sh
          cd cloud/portal
          meteor npm install
          meteor build ${{ runner.temp }}
      - name: Upload meteor bundle
        uses: actions/upload-artifact@v1
        with:
          name: bundle
          path: ${{ runner.temp }}/portal.tar.gz

  deploy:
    needs: buildPortal
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # see https://github.com/actions/checkout/tree/v2
      - uses: actions/checkout@v2

      - name: Download portal bundle
        uses: actions/download-artifact@v2
        with:
          name: bundle
          path: cloud/portal

      - name: Run portal install script
        run: |
          cd cloud/portal
          /bin/bash install.sh
