# deploy all but the portal, which has it's own (conditional) action
name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    # later change this to a specific branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # see https://github.com/actions/checkout/tree/v2
      - uses: actions/checkout@v2

      # - name: Set auth-token for npm
      #   env:
      #     BOT_AUTH_TOKEN: ${{ secrets.BOT_AUTH_TOKEN }}
      #   run: |
      #     echo "//registry.transitiverobotics.com/:_authToken=\"$BOT_AUTH_TOKEN\"" > ~/.npmrc

      - name: Prepare var folder
        run: |
          mkdir -p ~/var/certs
          mkdir -p ~/var/db
          mkdir -p ~/var/static

      - name: Copy env file
        run: |
          cp ~/var/production.env ~/transitive/cloud/.env

      - name: Run docker-compose build
        run: |
          cd ~/transitive/cloud
          docker-compose build

      - name: Run docker-compose up
        run: |
          cd ~/transitive/cloud
          docker-compose up -d
