# deploy all but the portal, which has it's own (conditional) action
name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    # later change this to a specific branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # see https://github.com/actions/checkout/tree/v2
      - uses: actions/checkout@v2

      - name: Run proxy install script
        run: |
          cd cloud/proxy
          /bin/bash install.sh

      - name: Run registry install script
        run: |
          cd cloud/registry
          /bin/bash install.sh

      - name: Run cloud app install script
        run: |
          cd cloud/app
          /bin/bash install.sh

      - name: Publish robot-agent if new version
        env:
          BOT_AUTH_TOKEN: ${{ secrets.BOT_AUTH_TOKEN }}
        run: |
          cd robot-agent
          echo "//registry.transitiverobotics.com/:_authToken=\"$BOT_AUTH_TOKEN\"" > ~/.npmrc
          /bin/bash republish.sh https://registry.transitiverobotics.com

      - name: Install ssh keys
        run: |
          cd cloud/system
          /bin/bash addKeys.sh
